### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by BoBeR182** [JFreegman/toxcrawler#2]
make                                                                                                                 [git][toxcrawler/crawler][masterU]
  CC    main.o
  LD    all
main.o: In function `crawler_new':
/home/bober/toxcore/toxcore/toxcrawler/crawler/./src/main.c:251: undefined reference to`DHT_callback_getnodes_response'
collect2: error: ld returned 1 exit status
make: **\* [Makefile:9: all] Error 1

**Comment by JFreegman** [comment]
Are you compiling it with my DHT-addon toxcore branch?

**Comment by BoBeR182** [comment]
Yup, I did `git checkout DHT-addon` after cloning it.

**Comment by JFreegman** [comment]
Did you `make clean` and rebuild/install it? Your error indicates that you're linked to the wrong toxcore branch.

**Comment by BoBeR182** [comment]
I don't know what else could be wrong. I have cleaned the directory and started from scratch several times.

**Comment by JFreegman** [comment]
Is it possible that you have more than one toxcore installation?

**Comment by BoBeR182** [comment]
Yes, as I have qTox installed from the Arch repos.

**Comment by JFreegman** [comment]
Packages shouldn't cause any issues. You need to figure out why it's not linking with the DHT-addon branch. Try uninstalling toxcore and see if you can still compile a client from source. If you can then you have more than one conflicting toxcore installations and need to sort that out first.

**Comment by BoBeR182** [comment]
On a brand new lubuntu install, I get this error

`virtualbox@virtualbox-VirtualBox:~/toxcore/toxcrawler/crawler$ ./crawler 
./crawler: error while loading shared libraries: libtoxcore.so.0: cannot open shared object file: No such file or directory`

It compiled fine, but now will not run.

**Comment by JFreegman** [comment]
`sudo ldconfig` should fix that
